# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_J6bWj2tTB_Zfoc22IIkD2P-QTm7_2wx
"""

pip install mahotas

pip install numpy --upgrade

import cv2
from google.colab.patches import cv2_imshow
import numpy as np
import mahotas

path = '/content/Fig0333(a)(test_pattern_blurring_orig).tif'
img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
cv2_imshow(img)

"""#Mean Filter Usign OpenCV Library#"""

filters = [3, 5, 7, 9, 15]
cv2_means = []
for i in filters:
  new_img = cv2.blur(img, (i,i))
  title = str(i) + ' * ' + str(i) + ' Mean-Filter'
  print(title)
  cv2_imshow(new_img)
  res_path = '/content/Mean-OpenCV-Results/' + str(i) + '*' + str(i) + 'Mean-Filter.jpg'
  cv2.imwrite(res_path, new_img)
  cv2_means.append(new_img)
  print(new_img)

print('3 Times 3*3 mean filter:')
new_img = img
for i in range(3):
  new_img = cv2.blur(new_img, (3, 3))
  title = str(i + 1) + ' 3*3 Mean-Filter:'
  print(title)
  cv2_imshow(new_img)
  print(new_img)
cv2.imwrite('/content/Mean-OpenCV-Results/3Times3*3Mean-Filter.jpg', new_img)
cv2_means.append(new_img)

"""#Mean Filter Using mahotas Library#"""

filters = [3, 5, 7, 9, 15]
mahotas_means = []
for i in filters:
  new_img = mahotas.mean_filter(img, i)
  title = str(i) + ' * ' + str(i) + ' Mean-Filter'
  print(title)
  cv2_imshow(new_img)
  res_path = '/content/Mean-mahotas-Results/' + str(i) + '*' + str(i) + 'Mean-Filter.jpg'
  cv2.imwrite(res_path, new_img)
  mahotas_means.append(new_img)
  print(new_img)

print('3 Times 3*3 mean filter:')
new_img = img
for i in range(3):
  new_img = mahotas.mean_filter(new_img, 3)
  title = str(i + 1) + ' 3*3 Mean-Filter:'
  print(title)
  cv2_imshow(new_img)
  print(new_img)
cv2.imwrite('/content/Mean-mahotas-Results/3Times3*3Mean-Filter.jpg', new_img)
mahotas_means.append(new_img)

"""#Gaussian Filter Using OpenCv Library#"""

filters = [3, 5, 7, 9, 15]
cv2_gauss = []
for i in filters:
  new_img = cv2.GaussianBlur(img,(i,i),0)
  title = str(i) + ' * ' + str(i) + ' Gaus-Filter'
  print(title)
  cv2_imshow(new_img)
  res_path = '/content/Gaussian-OpenCv-Results/' + str(i) + '*' + str(i) + 'Gaus-Filter.jpg'
  cv2.imwrite(res_path, new_img)
  cv2_gauss.append(new_img)
  print(new_img)

print('3 Times 3*3 Gaus filter:')
new_img = img
for i in range(3):
  new_img = cv2.GaussianBlur(new_img,(3, 3),0)
  title = str(i + 1) + ' 3*3 Gaus-Filter:'
  print(title)
  cv2_imshow(new_img)
  print(new_img)
cv2.imwrite('/content/Gaussian-OpenCv-Results/3Times3*Gaus-Filter.jpg', new_img)
cv2_gauss.append(new_img)

"""#Mean & Gaussian Filter Difference"""

print('Gaussian Filter Difference Between 9 *9 and 3 Times 3 * 3:')
diff_img = cv2_gauss[4] - cv2_gauss[5]
cv2_imshow(diff_img)
cv2.imwrite('/content/9*9And3Times3*3Difference/GaussianFilter.jpg', diff_img)

print('Mean Filter Difference Between 9 *9 and 3 Times 3 * 3:')
diff_img = cv2_means[4] - cv2_means[5]
cv2_imshow(diff_img)
cv2.imwrite('/content/9*9And3Times3*3Difference/MeanFilter.jpg', diff_img)

"""#Comparing Mean Filter & Gaussian Filter Of 3 * 3 With 5 * 5"""

print('Gaussian Filter Difference Between 3 *3 and 5 * 5:')
diff_img = cv2_gauss[0] - cv2_gauss[1]
cv2_imshow(diff_img)
cv2.imwrite('/content/3*3And5*5Difference/GaussianFilter.jpg', diff_img)

print('Mean Filter Difference Between 3 *3 and 5 * 5:')
cv2_imshow(cv2_means[0] - cv2_means[1])
cv2.imwrite('/content/3*3And5*5Difference/MeanFilter.jpg', diff_img)